import type { Metadata } from "next";

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "@/app/Provider"
import { Toaster } from "sonner";
// import LoadScript from "@/components/LoadScript";
import { VoiceProvider } from '@/components/VoiceContext'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
    <html lang="en">
      <body
        
      > 
        <Provider>
        {/* <LoadScript /> */}
        <VoiceProvider>

     
        {children}
        </VoiceProvider>
        <Toaster />
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
