import type { Metadata } from "next";

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "@/components/Provider"
import { Toaster } from "sonner";
// import LoadScript from "@/components/LoadScript";
import { VoiceProvider } from '@/components/VoiceContext'
import Script from 'next/script';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
    <html lang="en">
    <head>
    {/* <script src="https://cdn.botpress.cloud/webchat/v2.3/inject.js"></script>
<script src="https://files.bpcontent.cloud/2025/04/16/04/20250416044218-MS1G3FJ3.js"></script> */}
<Script
  src="https://cdn.botpress.cloud/webchat/v2.3/inject.js"
  strategy="afterInteractive" // Ensures it loads after the initial hydration
/>
<Script
  src="https://files.bpcontent.cloud/2025/04/16/04/20250416044218-MS1G3FJ3.js"
  strategy="afterInteractive"
/>

</head>
      
  
    
      <body
        
      > 
        <Provider>
        {/* <LoadScript /> */}
        <VoiceProvider>

     
        {children}
        </VoiceProvider>
        <Toaster />
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
